import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { format } from 'date-fns'

const BLUE  = '#2563EB'
const DARK  = '#1E293B'
const GRAY  = '#64748B'
const LIGHT = '#F8FAFC'

function header(doc, title, sub) {
  doc.setFillColor('#EFF6FF')
  doc.rect(0, 0, 210, 26, 'F')
  doc.setFillColor(BLUE)
  doc.rect(0, 0, 6, 26, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14); doc.setTextColor(DARK)
  doc.text('AcadEx', 14, 11)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8); doc.setTextColor(GRAY)
  doc.text('Academic Suite — Attendance', 14, 18)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12); doc.setTextColor(DARK)
  doc.text(title, 196, 11, { align: 'right' })
  if (sub) { doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(GRAY); doc.text(sub, 196, 18, { align: 'right' }) }
  doc.setDrawColor(BLUE); doc.setLineWidth(0.5); doc.line(0, 26, 210, 26)
}

function footer(doc) {
  const n = doc.internal.getNumberOfPages()
  for (let i = 1; i <= n; i++) {
    doc.setPage(i)
    doc.setDrawColor('#E2E8F0'); doc.setLineWidth(0.3); doc.line(14, 285, 196, 285)
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(GRAY)
    doc.text(`Generated by AcadEx on ${format(new Date(), 'PPpp')}`, 14, 291)
    doc.text(`Page ${i} of ${n}`, 196, 291, { align: 'right' })
  }
}

const tableStyle = {
  headStyles: { fillColor: [30, 41, 59], textColor: [240, 244, 255], fontStyle: 'bold', fontSize: 8 },
  bodyStyles: { fontSize: 8, textColor: [51, 65, 85] },
  alternateRowStyles: { fillColor: [248, 250, 252] },
  styles: { lineColor: [226, 232, 240], lineWidth: 0.2 },
}

export function exportDailyReportPDF(data, date) {
  const doc = new jsPDF()
  header(doc, 'Daily Attendance Report', format(new Date(date), 'EEEE, MMMM d, yyyy'))
  autoTable(doc, {
    startY: 34,
    head: [['Class', 'Total', 'Present', 'Absent', 'Late', 'Half-Day', 'Excused', 'Rate']],
    body: data.map(r => [r.class_name || `Class ${r.class_id}`, r.total, r.present, r.absent, r.late, r.half_day, r.excused, `${r.attendance_rate ?? 0}%`]),
    ...tableStyle,
    columnStyles: { 7: { halign: 'center', textColor: [5, 150, 105], fontStyle: 'bold' } },
  })
  footer(doc)
  doc.save(`daily-report-${date}.pdf`)
}

export function exportStudentReportPDF(student, summary, daily, from, to) {
  const doc = new jsPDF()
  header(doc, 'Student Attendance Report', `${format(new Date(from), 'MMM d')} – ${format(new Date(to), 'MMM d, yyyy')}`)
  doc.setFillColor(LIGHT); doc.roundedRect(14, 32, 182, 18, 2, 2, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(DARK)
  doc.text(student?.name || 'Student Report', 20, 40)
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(GRAY)
  doc.text(`No: ${student?.admission_number || '—'}`, 20, 46)
  const s = summary || {}
  const stats = [
    { l: 'Total', v: s.total_days ?? 0, c: BLUE },
    { l: 'Present', v: s.present_days ?? 0, c: '#059669' },
    { l: 'Absent', v: s.absent_days ?? 0, c: '#DC2626' },
    { l: 'Late', v: s.late_days ?? 0, c: '#D97706' },
    { l: 'Half-Day', v: s.half_days ?? 0, c: '#7C3AED' },
    { l: `${s.attendance_percent ?? 0}%`, v: 'Attendance', c: '#0891B2' },
  ]
  stats.forEach((st, i) => {
    const x = 14 + i * 31
    doc.setFontSize(12); doc.setFont('helvetica', 'bold'); doc.setTextColor(st.c)
    doc.text(String(st.v), x + 15, 62, { align: 'center' })
    doc.setFontSize(6); doc.setFont('helvetica', 'normal'); doc.setTextColor(GRAY)
    doc.text(st.l, x + 15, 68, { align: 'center' })
  })
  autoTable(doc, {
    startY: 76,
    head: [['Date', 'Status', 'Check-In', 'Check-Out', 'Remarks']],
    body: (daily || []).map(d => [format(new Date(d.attendance_date), 'EEE, MMM d yyyy'), d.status.toUpperCase(), d.check_in_time || '—', d.check_out_time || '—', d.remarks || '']),
    ...tableStyle,
    didParseCell: (data) => {
      if (data.column.index === 1 && data.section === 'body') {
        const map = { ABSENT: [220,38,38], PRESENT: [5,150,105], LATE: [217,119,6], HALF_DAY: [124,58,237] }
        if (map[data.cell.raw]) data.cell.styles.textColor = map[data.cell.raw]
      }
    },
  })
  footer(doc)
  doc.save(`student-report-${student?.admission_number || 'report'}.pdf`)
}

export function exportChronicAbsenteesPDF(data, from, to) {
  const doc = new jsPDF()
  header(doc, 'Chronic Absenteeism Report', `${format(new Date(from), 'MMM d')} – ${format(new Date(to), 'MMM d, yyyy')}`)
  doc.setFillColor('#FEF2F2'); doc.roundedRect(14, 32, 182, 12, 2, 2, 'F')
  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor('#DC2626')
  doc.text(`⚠  ${data.length} students flagged for chronic absenteeism`, 20, 40)
  autoTable(doc, {
    startY: 50,
    head: [['Student', 'Admission #', 'Class', 'Total Days', 'Absent', 'Absence %']],
    body: data.map(r => [r.student_name, r.admission_number || '—', r.class_name || '—', r.total_days, r.absent_days, `${r.absence_percent}%`]),
    ...tableStyle,
    columnStyles: { 5: { fontStyle: 'bold', textColor: [220, 38, 38] } },
  })
  footer(doc)
  doc.save(`chronic-absentees-${from}-${to}.pdf`)
}

export function exportTrendsPDF(data, from, to) {
  const doc = new jsPDF()
  header(doc, 'Attendance Trends Report', `${format(new Date(from), 'MMM d')} – ${format(new Date(to), 'MMM d, yyyy')}`)
  const avg = data.length ? (data.reduce((s, r) => s + (r.rate || 0), 0) / data.length).toFixed(1) : 0
  doc.setFont('helvetica', 'bold'); doc.setFontSize(32); doc.setTextColor(BLUE)
  doc.text(`${avg}%`, 105, 50, { align: 'center' })
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(GRAY)
  doc.text('Average Attendance Rate', 105, 58, { align: 'center' })
  autoTable(doc, {
    startY: 68,
    head: [['Date', 'Total Students', 'Attendance Rate']],
    body: data.map(r => [format(new Date(r.attendance_date), 'EEE, MMM d yyyy'), r.total, `${r.rate}%`]),
    ...tableStyle,
    columnStyles: { 2: { fontStyle: 'bold', textColor: [37, 99, 235] } },
  })
  footer(doc)
  doc.save(`attendance-trends-${from}-${to}.pdf`)
}
